// Code generated by "stringer -trimprefix DebugType -type DebugType"; DO NOT EDIT.

package pe

import "strconv"

const (
	_DebugType_name_0 = "UnknownCOFFCodeViewFPOMiscExceptionFixupOMapToSrcOMapFromSrcBorlandReserved10CLSID"
	_DebugType_name_1 = "Repro"
)

var (
	_DebugType_index_0 = [...]uint8{0, 7, 11, 19, 22, 26, 35, 40, 49, 60, 67, 77, 82}
)

func (i DebugType) String() string {
	switch {
	case 0 <= i && i <= 11:
		return _DebugType_name_0[_DebugType_index_0[i]:_DebugType_index_0[i+1]]
	case i == 16:
		return _DebugType_name_1
	default:
		return "DebugType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
