// Code generated by "stringer -trimprefix MachineType -type MachineType"; DO NOT EDIT.

package pe

import "strconv"

const _MachineType_name = "UnknownI386R4000WCEMIPSv2SH3SH3DSPSH4SH5ARMThumbARMNTAM33PowerPCPowerPCFPIA64MIPS16MIPSFPUMIPSFPU16EBCRISCV32RISCV64RISCV128AMD64M32RARM64"

var _MachineType_map = map[MachineType]string{
	0:     _MachineType_name[0:7],
	332:   _MachineType_name[7:11],
	358:   _MachineType_name[11:16],
	361:   _MachineType_name[16:25],
	418:   _MachineType_name[25:28],
	419:   _MachineType_name[28:34],
	422:   _MachineType_name[34:37],
	424:   _MachineType_name[37:40],
	448:   _MachineType_name[40:43],
	450:   _MachineType_name[43:48],
	452:   _MachineType_name[48:53],
	467:   _MachineType_name[53:57],
	496:   _MachineType_name[57:64],
	497:   _MachineType_name[64:73],
	512:   _MachineType_name[73:77],
	614:   _MachineType_name[77:83],
	870:   _MachineType_name[83:90],
	1126:  _MachineType_name[90:99],
	3772:  _MachineType_name[99:102],
	20530: _MachineType_name[102:109],
	20580: _MachineType_name[109:116],
	20776: _MachineType_name[116:124],
	34404: _MachineType_name[124:129],
	36929: _MachineType_name[129:133],
	43620: _MachineType_name[133:138],
}

func (i MachineType) String() string {
	if str, ok := _MachineType_map[i]; ok {
		return str
	}
	return "MachineType(" + strconv.FormatInt(int64(i), 10) + ")"
}
