// Code generated by "stringer -trimprefix Subsystem -type Subsystem"; DO NOT EDIT.

package pe

import "strconv"

const (
	_Subsystem_name_0 = "UnknownNativeWindowsGUIWindowsCUI"
	_Subsystem_name_1 = "OS2CUI"
	_Subsystem_name_2 = "PosixCUINativeWindowsWindowsCEGUIEFIApplicationEFIBootServiceDriverEFIRuntimeDriverEFIRomXbox"
	_Subsystem_name_3 = "WindowsBootApplication"
)

var (
	_Subsystem_index_0 = [...]uint8{0, 7, 13, 23, 33}
	_Subsystem_index_2 = [...]uint8{0, 8, 21, 33, 47, 67, 83, 89, 93}
)

func (i Subsystem) String() string {
	switch {
	case 0 <= i && i <= 3:
		return _Subsystem_name_0[_Subsystem_index_0[i]:_Subsystem_index_0[i+1]]
	case i == 5:
		return _Subsystem_name_1
	case 7 <= i && i <= 14:
		i -= 7
		return _Subsystem_name_2[_Subsystem_index_2[i]:_Subsystem_index_2[i+1]]
	case i == 16:
		return _Subsystem_name_3
	default:
		return "Subsystem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
