// Code generated by "stringer -trimprefix BaseRelocType -type BaseRelocType"; DO NOT EDIT.

package enum

import "strconv"

const _BaseRelocType_name = "AbsoluteHighLowHighLowHighAdjMipsJmpAddrReserved6ThumbMov32RISCVLow12sMIPSJmpAddr16Dir64"

var _BaseRelocType_index = [...]uint8{0, 8, 12, 15, 22, 29, 40, 49, 59, 70, 83, 88}

func (i BaseRelocType) String() string {
	if i >= BaseRelocType(len(_BaseRelocType_index)-1) {
		return "BaseRelocType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BaseRelocType_name[_BaseRelocType_index[i]:_BaseRelocType_index[i+1]]
}
