// Code generated by "stringer -trimprefix DLLCharacteristic -type DLLCharacteristic"; DO NOT EDIT.

package enum

import "strconv"

const _DLLCharacteristic_name = "sReserved0001sReserved0002sReserved0004sReserved0008sHighEntropyVAsDynamicBasesForceIntegritysNXCompatsNoIsolationsNoSEHsNoBindsAppContainersWDMDriversGuardCFsTerminalServerAware"

var _DLLCharacteristic_map = map[DLLCharacteristic]string{
	1:     _DLLCharacteristic_name[0:13],
	2:     _DLLCharacteristic_name[13:26],
	4:     _DLLCharacteristic_name[26:39],
	8:     _DLLCharacteristic_name[39:52],
	32:    _DLLCharacteristic_name[52:66],
	64:    _DLLCharacteristic_name[66:78],
	128:   _DLLCharacteristic_name[78:93],
	256:   _DLLCharacteristic_name[93:102],
	512:   _DLLCharacteristic_name[102:114],
	1024:  _DLLCharacteristic_name[114:120],
	2048:  _DLLCharacteristic_name[120:127],
	4096:  _DLLCharacteristic_name[127:140],
	8192:  _DLLCharacteristic_name[140:150],
	16384: _DLLCharacteristic_name[150:158],
	32768: _DLLCharacteristic_name[158:178],
}

func (i DLLCharacteristic) String() string {
	if str, ok := _DLLCharacteristic_map[i]; ok {
		return str
	}
	return "DLLCharacteristic(" + strconv.FormatInt(int64(i), 10) + ")"
}
